### ISSUE TITLE
Lists classifying

### ISSUE THREAD

**Issue by Nedudi** [andrey-p/markdown-it-classy#4]
Hi, Andrey!
I am wondering if it possible to change the behaviour of lists same as other block elements.
For example - I was expecting something like this 

```
- bobby {active}
- kenny {active}
- robin {inactive}
{huge-list}


<ul class="huge-list">
    <li class="active">bobby</li>
    <li class="active">kenny</li>
    <li class="inactive">robin</li>
</ul>
```

Thank you

**Comment by andrey-p** [comment]
That's definitely a thing this module should be doing. I'll look into it.

**Comment by andrey-p** [comment]
@Nedudi Fixed in 0.1.0, now in Bower and NPM repositories near you.

There's a little gotcha with using this for lists and blockquotes, check the readme: https://github.com/andrey-p/markdown-it-classy#nested-elements

**Comment by Nedudi** [comment]
Looks like I still have the same problem

```
$ bower install markdown-it-classy  --save
bower markdown-it-classy#~0.1.0 cached git://github.com/andrey-p/markdown-it-classy.git#0.1.0
bower markdown-it-classy#~0.1.0         validate 0.1.0 against git://github.com/andrey-p/markdown-it-    classy.git#~0.1.0
bower markdown-it-classy#*                cached git://github.com/andrey-p/markdown-it-classy.git#0.1.0
bower markdown-it-classy#*              validate 0.1.0 against git://github.com/andrey-p/markdown-it-    classy.git#*
bower markdown-it-classy#~0.1.0          install markdown-it-classy#0.1.0
```

and 

![image](https://cloud.githubusercontent.com/assets/702557/6543520/c5b51d96-c52f-11e4-817c-85a98f510833.png)

**Comment by Nedudi** [comment]
Looks like it just did not packed for bower, 

version in /dist is old
at the same time version from index.js is working very well!!! Awesome

Could you just distribute bower package with new version?

Thanks!

**Comment by andrey-p** [comment]
@Nedudi Sorry about that! I've updated dist now, check v0.1.1.

I'll see if there's some kind of tests I can put in place to prevent this from happening again.
